const FIELD_TYPES = {
  SINGLE_TEXT: "SINGLE_TEXT",
  MULTI_TEXT: "MULTI_TEXT",
  NUMBER: "NUMBER",
  DOCUMENT_LINK: "DOCUMENT_LINK",
  BOOLEAN: "BOOLEAN",
};

const FIELD_TYPE_LIMITS = {
  [FIELD_TYPES.SINGLE_TEXT]: 3,
  [FIELD_TYPES.MULTI_TEXT]: 3,
  [FIELD_TYPES.NUMBER]: 3,
  [FIELD_TYPES.DOCUMENT_LINK]: 3,
  [FIELD_TYPES.BOOLEAN]: 3,
};

const FIELD_TYPE_LABELS = {
  [FIELD_TYPES.SINGLE_TEXT]: "Single-line Text",
  [FIELD_TYPES.MULTI_TEXT]: "Multi-line Text",
  [FIELD_TYPES.NUMBER]: "Number",
  [FIELD_TYPES.DOCUMENT_LINK]: "Document/Image Link",
  [FIELD_TYPES.BOOLEAN]: "True/False",
};

module.exports = { FIELD_TYPES, FIELD_TYPE_LIMITS, FIELD_TYPE_LABELS };
