const ID_ELEMENTS = {
  FIXED_TEXT: 'FIXED_TEXT',
  RANDOM_20: 'RANDOM_20',
  RANDOM_32: 'RANDOM_32',
  RANDOM_6: 'RANDOM_6', 
  RANDOM_9: 'RANDOM_9',
  GUID: 'GUID',
  DATETIME: 'DATETIME',
  SEQUENCE: 'SEQUENCE'
};

module.exports = {ID_ELEMENTS}